### PR TITLE
Add 3D Touch to Care Card and Connect

### PR DESCRIPTION
**Pull request by tktsubota**
#78

### CODE REVIEW

**Comment by umerkhan-apple** [comment]
@tktsubota Perfect! Thanks for the quick turnaround! 👍

**Comment by smravca-apple** [comment]
Hi @tktsubota!  Could you please provide me with a contact email so that I can send you a contribution agreement to sign?  Thank you! :)

**Comment by tktsubota** [comment]
@smravca-apple You can contact me at troy.tsubota@gmail.com

**Comment by tktsubota** [comment]
@smravca-apple Should I make a new pull request addressing the licensing and then reply to your email? I also have some minor optimizations I want to add.

**Pull request merged**
