### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by erik-apple**
This PR closes out #474 and #472.

### CODE REVIEW

**Comment by muhammad-Ahmed-sudo** [comment]
i am still having this issues as described. added careKit by SPM 
Screenshot 2021-08-29 at 2 29 45 PM

**Comment by erik-apple** [comment]
It looks like you maybe be using the current release of Xcode 12. The main branch is a beta that only compiles on Xcode 13 beta. (It is still compatible with earlier versions of iOS though)

**Comment by muhammad-Ahmed-sudo** [comment]
> It looks like you maybe be using the current release of Xcode 12. The main branch is a beta that only compiles on Xcode 13 beta. (It is still compatible with earlier versions of iOS though)

is it possible to upload build on app store connect using xcode beta.

**Comment by erik-apple** [comment]
No, it is not. You’ll have to wait until Xcode 13’s release.

**Pull request merged**
