### PR TITLE
Add currentPage, reload, pull-to-refresh to OCKDailyPageViewController

### PR DESCRIPTION
**Pull request by erik-apple**
This PR adds pull-to-refresh to `OCKDailyPageViewController`. It includes one new public property and one new public method. This PR should help with #476.

```swift
open class OCKDailyPageViewController {

    // ...

    /// The page that is currently being displayed.
    open var currentPage: OCKListViewController?

    /// Reload the contents at the currently selected date.
    open func reload()

    // ...
}

```

### CODE REVIEW

**Comment by tommysarni** [comment]
This PR would be super helpful to me, whenever you can get this done

**Comment by tommysarni** [comment]
Thanks guys !!

**Comment by sethjberkowitz** [comment]
Very excited about this feature!  We're getting build errors on carekit-apple:master similar to #491

**Comment by erik-apple** [comment]
@sethjberkowitz Are you running the most recent version of Xcode beta?

**Comment by sethjberkowitz** [comment]
@erik-apple No, I was using Xcode 11.  Now I'm fighting with SPM in Xcode 12 beta.  Getting multiple errors like
`Cannot find type 'OCKStore' in scope`

Any suggestions?

**Comment by erik-apple** [comment]
Have you imported `CareKitStore`, or just `CareKit`?

**Comment by sethjberkowitz** [comment]
Was just importing CareKit... "in scope" errors fixed!

**Pull request merged**
