### PR TITLE
Update connect header when OCKPatient is set

### PR DESCRIPTION
**Pull request by xmlmodeling**
Fixes bug where OCKConnectHeaderView is not updated if _patient is set after view is prepared, or if _patient is modified to a different OCKPatient. And related bug where header image is not set to nil when changed OCKPatient has no image.

### CODE REVIEW

**Comment by kelseydedoshka-apple** [comment]
@xmlmodeling - changes look great. Do you mind separating them out from the ResearchKit submodule update?

**Comment by xmlmodeling** [comment]
Hi Kelsey, thanks for your review and sorry for my delay.  I've been on a lot of business travel this past month.  I will close this PR, sync my repo, and submit a new PR.

Thanks!
  Dave

**Comment by kelseydedoshka-apple** [comment]
@xmlmodeling - thanks Dave, looking forward to seeing the new PR!

**Comment by xmlmodeling** [comment]
Replaced with updated PR.

**Pull request closed without merging**
