### PR TITLE
CareKit 2.1 beta

### PR DESCRIPTION
**Pull request by erik-apple**
## CareKit 2.1 Release Notes

*CareKit 2.1* supports *iOS* and *watchOS* and requires *Xcode 12.0* or later. The minimum supported *Base SDK* is *13.0* for *iOS* and *7.0* for *watchOS*.

*CareKit 2.1* includes the following new features and enhancements.

### New Views
- SimpleTaskView (SwiftUI)
- InstructionsTaskView (SwiftUI)
- LabeledValueTaskView (SwiftUI)
- NumericProgressTaskView (SwiftUI)
- LinkView (SwiftUI)
- OCKFeaturedContentView (UIKit)
- DetailView enhancements (UIKit)

### watchOS Support
- CareKit, CareKitUI, CareKitStore and the new CareKitFHIR now build for watchOS

### HealthKit Driven Tasks
- HealthKit data can now be used to autocomplete CareKit tasks
- OCKStoreCoordinator
- OCKHealthKitPassthroughStore
- OCKHealthKitTask & OCKHealthKitOutcome

### FHIR Compatibility
- A new package, CareKitFHIR, for converting to and from FHIR resources
- Support for DSTU2 Patient, CarePlanActivity, and MedicationOrder resources
- Support for R4 Patient resources

### Remote Synchronization
- Extension on OCKStore for synchronization with a remote server
- OCKRemoteSynchronizable protocol for adding new integrations
- OCKWatchConnectivityPeer for synchronizing a store on watchOS with a store on iOS

### Miscellaneous
- Updated sample app
- Enhanced catalog app
- Minor bug fixes

### CODE REVIEW

**Comment by martinstoyanov** [comment]
Thank you! Will CardView be available in UIKit as well?

**Comment by erik-apple** [comment]
The card view is available in our UIKit API as the `OCKCardable` protocol.
https://github.com/carekit-apple/CareKit/blob/master/CareKitUI/CareKitUI/iOS/OCKCardable.swift

**Comment by martinstoyanov** [comment]
@erik-apple Thank you. Is there an equivalent of `NumericProgressTaskView` for UIKit? I suppose no?

**Comment by erik-apple** [comment]
Unfortunately not. That one is a SwiftUI only API.
Your best bet is to wrap it in a `UIHostingController` for use in UIKit contexts.

**Comment by daveshah** [comment]
Any insight into when this will move from beta to an official 2.1 release?

**Comment by gavirawson-apple** [comment]
Great question! We've been watching SwiftUI evolve and have been hard at work exploring our SwiftUI API and story. We plan on releasing a beta version of that work in the next few months, essentially an improvement to this API that is even easier to use. We're excited for you to play around with it and give us feedback, then we will move to an official release.

**Comment by drdavec** [comment]
I look forward to testing that next iteration of CareKit API.  I am all in
with SwiftUI for every aspect of my app development and would like to avoid
duplications and workarounds for getting SwiftUI integrated with CareKit
that conflict with your proposed next steps.  Thanks for your continued
support on this project!!

Dave

**Comment by gavirawson-apple** [comment]
Great to hear! And thank you for all your contributions! 

Hang tight and we'll post a branch as soon as it's ready. In the meantime, if there are specific examples you're working on where you're concerned about duplication, let us know and we can try and provide some guidance.

**Pull request merged**
