### PR TITLE
Typo in Russian localization

### PR DESCRIPTION
**Pull request by yas375**
https://en.wikipedia.org/wiki/Yo_(Cyrillic)

https://ru.wiktionary.org/wiki/отчёт
https://en.wiktionary.org/wiki/отчёт

### CODE REVIEW

**Comment by umerkhan-apple** [comment]
All localization PRs were reviewed Apple's Localization team. Any suggestions that seemed appropriate were incorporated in CK 1.1.

**Comment by yas375** [comment]
The issue wasn't fixed. Is it possible to hear rationale why this is one is not appropriate?

**Comment by umerkhan-apple** [comment]
@yas375 Let me reach out to the team and see if I can find out. Re-opening the PR until then.

**Comment by srinathtm-apple** [comment]
Closing out PRs that are no longer relevant due to the CareKit 2.0 beta update.

**Pull request closed without merging**
