### PR TITLE
Removed "#if swift(>=5.5)" now that Xcode 13 is supported by CI.

### PR DESCRIPTION
**Pull request by JWStaiert**
https://github.com/carekit-apple/CareKit/issues/619

Updated source and workflow script.

### CODE REVIEW

**Comment by erik-apple** [comment]
It looks like CI is failing because the iPhone model specified in `swift.yml` isn't installed on the CI system.

Maybe we could try `{ platform:iOS Simulator, OS:15.0, name:iPhone 12 Pro Max }` instead.
```
Run set -o pipefail && env NSUnbufferedIO=YES xcodebuild -verbose -workspace CKWorkspace.xcworkspace -scheme CareKit\ iOS -destination platform=iOS\ Simulator,OS=14.4,name=iPhone\ 11\ Pro\ Max build test | xcpretty
4
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
5
		{ platform:iOS Simulator, OS:14.4, name:iPhone 11 Pro Max }
6

7
	The requested device could not be found because no available devices matched the request.
8

9
	Available destinations for the "CareKit iOS" scheme:
10
		{ platform:macOS, arch:x86_64, variant:Mac Catalyst, id:4203018E-580F-C1B5-9525-B745CECA79EB }
11
		{ platform:iOS Simulator, id:00C5043D-C8EC-479B-84B2-BC5DB252EB95, OS:15.0, name:iPad (7th generation) }
12
		{ platform:iOS Simulator, id:D91BA056-AC2D-4B72-AA96-2C290D5AC920, OS:15.0, name:iPad (8th generation) }
13
		{ platform:iOS Simulator, id:9570F9EA-6AE3-40EE-A398-32F9AE551BD8, OS:15.0, name:iPad Air (3rd generation) }
14
		{ platform:iOS Simulator, id:BD6D7C0C-76FF-4659-BF61-DE825F8B07F4, OS:15.0, name:iPad Air (4th generation) }
15
		{ platform:iOS Simulator, id:10D6F508-A439-41A1-9427-89A78E44AEF3, OS:15.0, name:iPad Pro (9.7-inch) }
16
		{ platform:iOS Simulator, id:3DAC2F7B-E1FB-4743-873B-C9B999E5AAA5, OS:15.0, name:iPad Pro (11-inch) (2nd generation) }
17
		{ platform:iOS Simulator, id:0BB27890-6D90-46F3-9608-D2F6C8B1DBF8, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
18
		{ platform:iOS Simulator, id:7414E29A-FF2F-41F1-A729-16A47A09F5E8, OS:15.0, name:iPad Pro (12.9-inch) (4th generation) }
19
		{ platform:iOS Simulator, id:B3F77622-1950-4C28-A4DB-934D48DDA9EB, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
20
		{ platform:iOS Simulator, id:36AE5D7B-478E-42C6-B71D-CAB94672141E, OS:15.0, name:iPhone 8 }
21
		{ platform:iOS Simulator, id:254ED496-4431-428A-BEE3-FF760A00164B, OS:15.0, name:iPhone 8 Plus }
22
		{ platform:iOS Simulator, id:D33FBEB1-33F4-47A7-A35D-1D945829AE92, OS:15.0, name:iPhone 11 }
23
		{ platform:iOS Simulator, id:FEAB0D77-7B88-4D74-AE59-D5C6CAD5D5C1, OS:15.0, name:iPhone 11 Pro }
24
		{ platform:iOS Simulator, id:E73A1C68-986F-40C4-B1A5-1F482227C1DF, OS:15.0, name:iPhone 11 Pro Max }
25
		{ platform:iOS Simulator, id:8E8D579C-E558-447D-8D95-7B0AA1B6A3B6, OS:15.0, name:iPhone 12 }
26
		{ platform:iOS Simulator, id:EDA4E2F9-032E-474A-A033-7484805FAC1E, OS:15.0, name:iPhone 12 Pro }
27
		{ platform:iOS Simulator, id:E526CC47-8C22-430F-A6A4-2272E612608E, OS:15.0, name:iPhone 12 Pro Max }
28
		{ platform:iOS Simulator, id:59211C33-9673-4A78-AF8D-CD8952183CCF, OS:15.0, name:iPhone 12 mini }
29
		{ platform:iOS Simulator, id:7A60DC01-988E-4068-B9CF-CEFE1F8FF07E, OS:15.0, name:iPhone SE (2nd generation) }
30
		{ platform:iOS Simulator, id:EF78A681-D496-4509-AE8B-91654EBB17C1, OS:15.0, name:iPod touch (7th generation) }
31

32
	Ineligible destinations for the "CareKit iOS" scheme:
33
		{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
34
		{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
35
		{ platform:macOS, variant:Mac Catalyst, name:Any Mac }
36
Error: Process completed with exit code 70.
```

**Review by erik-apple — CHANGES_REQUESTED** [review]
Looks like you need to upgrade the simulator device. For whatever reason the iPhone 11 Pro Max isn't included in CI's installation of Xcode by default.

**Comment by erik-apple** [comment]
Adding @cbaker6 for a second set of eyes.

**Comment by JWStaiert** [comment]
According to the github CI info page for macOS 11.5, only iOS 15 is installed for Xcode 13.

Also, I had to set the 'runs-on' property to 'macos-11'. It's unclear to me why 'macos-latest' doesn't resolve to 'macos-11', but most of this is new to me.

**Review by erik-apple — APPROVED** [review]

**Comment by erik-apple** [comment]
Looks like it's working now! Thanks for figuring it out!

**Comment by erik-apple** [comment]
> It's unclear to me why 'macos-latest' doesn't resolve to 'macos-11'

I'm not sure either. Big Sur is the latest release. GitHub may have their own definitions, or it may be a bug. In either case, great work on this PR!

**Comment by erik-apple** [comment]
This closes #621.

**Pull request merged**
