### PR TITLE
Fix fetchTaskById to return the newest version of a task

### PR DESCRIPTION
**Pull request by nizar**
fix for #545

### CODE REVIEW

**Comment by nizar** [comment]
@erik-apple any ETA on getting this merged?

**Comment by cbaker6** [comment]
@nizar I believe you may have merged from main branch incorrectly as it's showing commits from @erik-apple and myself along with having us as participants to this PR though I didn't contribute code here. If you rebase with main and then merge those changes to this branch, it should only show your current commits as oppose to counting commits already made to the main branch

**Comment by nizar** [comment]
@cbaker6 Thanks for catching this. I messed up the merge. I'll clean it up and update.

**Comment by nizar** [comment]
Closing this and will resubmit a new pull request with clean commits

**Pull request closed without merging**
