### PR TITLE
Issue #619 - Remove "#if swift(>=5.5)" once Xcode 13 supported by CI

### PR DESCRIPTION
**Pull request by JWStaiert**
Revised source and updated CI script.

### CODE REVIEW

**Comment by cbaker6** [comment]
To prevent merge conflicts, you should fork from the latest main and make your changes in a new branch. You are currently using the branch from your old PR which all of your commits have been “squashed and merged”

**Comment by erik-apple** [comment]
Yep, Corey is correct! You'll want to branch from `main` and apply your changes on top of that. You may find the git commands `rebase` or `cherrypick` to be helpful!

**Comment by JWStaiert** [comment]
Okay. I will have time to make that change this evening.

**Comment by JWStaiert** [comment]
Am having trouble with rebase, will close this PR and create a new branch from head of main.

**Pull request closed without merging**
