### PR TITLE
Fixed instance of 'OCKCarePlan' where it should be 'OCKHealthKitTask'

### PR DESCRIPTION
**Pull request by npsantini**
The documentation is wrong here in OCKHealthKitTask.swift

It instantiates a new OCKHealthKitTask.

### CODE REVIEW

**Review by erik-apple — APPROVED** [review]
Thanks for the fix!

**Comment by cbaker6** [comment]
@erik-apple, @npsantini is an undergrad CS student in my course and is using CareKit for his final project.

The doc corrections he found here are also in OCKTask, do you want him to apply those fixes along with updating `title` for both as well?

**Comment by cbaker6** [comment]
@npsantini you will probably need to open another PR to add the other updates since this one is merged

**Comment by npsantini** [comment]
> @npsantini you will probably need to open another PR to add the other updates since this one is merged

@ZachJBurns is working on the other fix.

**Pull request merged**
