### PR TITLE
Added isGrouped and isSorted properties to Care Card, Symptoms Tracker, Care Contents

### PR DESCRIPTION
**Pull request by ninoguba**
This allows activities to be grouped/ungrouped and sorted/unsorted in the Care Card, Symptom Tracker, and the new Care Content views.

The default setting for these new properties is YES.

Setting both to NO will allow the activities on the Care Card and Symptom Tracker views to present like it was before prior to CK 1.2.

### CODE REVIEW

**Comment by akshay-yadav-apple** [comment]
Hey @ninoguba,
Thanks for contributing the PR for issue #183.
Could you please resolve the merge conflicts and push again, before we can review the PR?

Thanks.

**Comment by ninoguba** [comment]
@akshay-yadav-apple conflicts resolved.

**Comment by ninoguba** [comment]
@akshay-yadav-apple corrected the merge to master.  conflicts resolved.  you can now do the review. thanks!

**Comment by Pariecemckinney-apple** [comment]
@ninoguba Looks good on my end.

@akshay-yadav-apple, could you take a look also

**Comment by akshay-yadav-apple** [comment]
@ninoguba 
Hey! The PR looks good in terms of code. Can we have a little more description of the isGrouped and isSorted properties. To emphasize that isSorted will sort alphabetically, and isGrouped will group by ignoring section headers.

**Comment by ninoguba** [comment]
@akshay-yadav-apple ok will add a little more description to these new properties soon.

**Comment by Pariecemckinney-apple** [comment]
@ninoguba, Thank you for the PR. Merging now.

**Comment by jmaratt** [comment]
@ninoguba, thank you for contributing this.  I've used the group identifiers in the same way you have for my project.

@Pariecemckinney-apple, was there a problem with this merge?

**Comment by Pariecemckinney-apple** [comment]
@jmaratt - none at all. Final test was needed. Thanks for checking!

**Pull request merged**
