### PR TITLE
Add completion to log button

### PR DESCRIPTION
**Pull request by tommysarni**
I need a new View Controller to pop up when pressing the Log Button, but still like the idea of the logging when the button was pressed. In order to keep protection, I simply created a function property for the OCKButtonLogTaskView.

### CODE REVIEW

**Comment by tommysarni** [comment]
@erik-apple Can you review this PR and if this is not possible can you please guide me in how to create my own TaskViewController. Thanks so much

**Comment by erik-apple** [comment]
I think subclassing is the route you should probably go! 

Try out something like this.

```swift
class TommyTaskViewController: OCKButtonLogTaskViewController {
    
    override func taskView(_ taskView: UIView & OCKTaskDisplayable,
                           didCompleteEvent isComplete: Bool,
                           at indexPath: IndexPath, sender: Any?) {
        
        // Do what the superclass does (log new outcome, delete outcome)
        super.taskView(taskView, didCompleteEvent: isComplete, at: indexPath, sender: sender)
        
        // Plus insert your extra code here (only when completing a new outcome)
        if isComplete {
            let someViewController = UIViewController()
            present(someViewController, animated: true, completion: nil)
        }
    }
}

**Comment by tommysarni** [comment]
Awesome, I'll try it out and let you know how it goes !

**Comment by erik-apple** [comment]
@tommysarni How did that work out? Is it okay to close this PR?

**Comment by tommysarni** [comment]
@erik-apple Oh so sorry totally forgot to update, yeah subclassing worked perfectly. Thanks so much !

**Comment by erik-apple** [comment]
Great! I'll close this out then!

**Pull request closed without merging**
